
use customer_behaviour;
SELECT * FROM customer LIMIT 20;

-- 1. Total revenue generated by male and female

select gender, SUM(purchase_amount) as revenue
from customer
group by gender;


-- 2. Customer who spend more than average after discount applied.

select customer_id, purchase_amount
from customer
where discount_applied = 'yes' AND purchase_amount >= (select AVG(purchase_amount) from customer);


-- 3. Top 5 products has highest average review rating

select item_purchased, Round(AVG(review_rating), 2) as 'Average_product_Rating'
from customer
group by item_purchased
order by Average_product_Rating desc
limit 5;


-- 4.Average Purchase Amounts between Standard and Express Shipping

select shipping_type, 
ROUND(avg(purchase_amount),2) as Average_purchase_Amount 
from customer
where shipping_type in ('Standard','Express')
group by shipping_type;


-- 5.Average spend and total revenue between subscribers and non-subscribers

select subscription_status,
COUNT(customer_id) as total_customer,
ROUND (avg(purchase_amount),2) as avg_spend,
ROUND (sum(purchase_amount),2) as total_revenue
from customer
group by  subscription_status;
-- order by total_revenue, avg_spend desc;

-- 6.Top 5 products have the highest percentage of purchases with discounts applied

select item_purchased,
ROUND(100 * sum(case when discount_applied = 'yes' then 1 else 0 end)/count(*),2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc limit 5;

-- 7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment

with customer_type as(
select customer_id,previous_purchases,
case
	when previous_purchases = 1 then 'New'
	when previous_purchases between 2 and 10 then 'Returning'
    else 'Loyal'
    end as customer_segment
from customer
)

select customer_segment, count(*) as 'Number_of_customer'
from customer_type
group by customer_segment;


-- 8. The top 3 most purchased products within each category

with item_counts as(
select category, item_purchased,
count(customer_id) as total_orders,
Row_number() over(partition by category order by count(customer_id) desc) as item_rank
from customer
group by category, item_purchased
)

select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <=3;

-- 9. customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe or not

select subscription_status,
count(customer_id) as repeat_byers
from customer
where previous_purchases >5
group by subscription_status;



-- 10.Revenue contribution of each age group
  
select age_group,
sum(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc





